// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/gen-project-meta.ts

export const projectMeta = {
  "novogradnja-objekta-vila-rozna-dolina-condominium": {
    "categories": ["Javni objekti", "Stanovanjski objekti"],
    "client": "ASSETCO d.o.o.",
    "location": "Večna pot 81, Ljubljana",
    "workType": "",
    "year": ""
  },
  "salon-pohistva-in-hotel-nox": {
    "categories": [
      "Javni objekti",
      "Poslovno industrijski objekti"
    ],
    "client": "HIT PRELESS d.o.o.",
    "location": "Ljubljana - Vižmarje",
    "workType": "Novogradnja hotela",
    "year": "2023"
  },
  "hotel-cubo": {
    "categories": [
      "Javni objekti",
      "Poslovno industrijski objekti"
    ],
    "client": "Hotel Cubo d.o.o.",
    "location": "Ljubljana",
    "workType": "Rekonstrukcija",
    "year": ""
  },
  "vila-madeleine": {
    "categories": [
      "Javni objekti"
    ],
    "client": "ANDE INVEST in MB INVESTICIJE PLUS",
    "location": "Ljubljana",
    "workType": "GOI dela ter dobava in montaža opreme",
    "year": ""
  },
  "izvedba-obnove-stavbe-vila-zlatica-v-ljubljani": {
    "categories": [
      "Javni objekti"
    ],
    "client": "MESTNA OBČINA LJUBLJANA",
    "location": "Ljubljana",
    "workType": "",
    "year": ""
  },
  "izvedba-gradbeno-obrtniskih-in-instalacijskih-del-ter-zunanje-ureditve-pri-gradnji-objekta-na-stolbi-8-v-ljubljani": {
    "categories": [
      "Javni objekti"
    ],
    "client": "Mestna občina Ljubljana",
    "location": "Ljubljana",
    "workType": "",
    "year": ""
  },
  "center-obala-debeli-rtic": {
    "categories": [
      "Javni objekti",
      "Stanovanjski objekti"
    ],
    "client": "Ministrstvo za delo, družino in socialne zadeve",
    "location": "Debeli Rtič",
    "workType": "Novogradnja",
    "year": ""
  },
  "pionirski-dom-art-center": {
    "categories": [
      "Javni objekti",
      "Objekti kulturne dediščine"
    ],
    "client": "Mestna občina Ljubljana",
    "location": "Ljubljana",
    "workType": "Obnova strehe in strešne konstrukcije na spomeniškovarstvenem objektu (objekt kulturne dediščine) in obnova fasade na spomeniškovarstvenem objektu (objekt kulturne dediščine) - izvedba GOI del za rekonstrukcijo objekta",
    "year": ""
  },
  "svicarija": {
    "categories": [
      "Javni objekti",
      "Objekti kulturne dediščine"
    ],
    "client": "Mestna občina Ljubljana",
    "location": "Ljubljana",
    "workType": "Obnova strehe in strešne konstrukcije na spomeniškovarstvenem objektu (objekt kulturne dediščine) in obnova fasade na spomeniškovarstvenem objektu (objekt kulturne dediščine) - izvedba GOI del obnove stavbe",
    "year": ""
  },
  "izvedba-goi-del-ter-zu-za-objekt-cetrtne-skupnosti-golovec-v-ljubljani": {
    "categories": [
      "Javni objekti",
      "Stanovanjski objekti"
    ],
    "client": "MESTNA OBČINA LJUBLJANA",
    "location": "Ljubljana – Golovec",
    "workType": "",
    "year": ""
  },
  "hisa-soncek-vincarjeva": {
    "categories": [
      "Javni objekti",
      "Stanovanjski objekti"
    ],
    "client": "Javni stanovanjski sklad Mestne občine Ljubljana",
    "location": "Ljubljana",
    "workType": "Izgradnja stanovanjske stavbe",
    "year": ""
  },
  "gradnja-vrtca-v-bohinjski-bistrici": {
    "categories": [
      "Javni objekti",
      "Vrtci"
    ],
    "client": "Občina Bohinj",
    "location": "Bohinjska Bistrica",
    "workType": "Izvedba gradbeno obrtniških in inštalacijskih del za gradnjo vrtca",
    "year": ""
  },
  "projektiranje-in-gradnja-montaznega-vrtca-grgar": {
    "categories": [
      "Javni objekti",
      "Vrtci"
    ],
    "client": "Mestna občina Nova Groica",
    "location": "Nova Gorica",
    "workType": "Projektiranje in gradnja montažnega vrtca",
    "year": ""
  },
  "projektiranje-in-izgradnja-montaznega-lesenega-stanovanjsko-poslovnega-kompleksa-polje-iv": {
    "categories": [
      "Javni objekti",
      "Stanovanjski objekti"
    ],
    "client": "Javno stanovanjski sklad Mestne občine Ljubljana",
    "location": "Ljubljana - Polje",
    "workType": "Projektiranje in izgradnja stanovanjsko - poslovnega kompleksa",
    "year": "2017"
  },
  "zmajev-brlog-na-ljubljanskem-gradu": {
    "categories": [
      "Javni objekti",
      "Objekti kulturne dediščine"
    ],
    "client": "Javni zavod Ljubljanski grad",
    "location": "Ljubljanski grad, Ljubljana",
    "workType": "GOI dela pri obnovi prostorov",
    "year": "2017"
  },
  "hribarjeva-dvorana-na-ljubljanskem-gradu": {
    "categories": [
      "Javni objekti",
      "Objekti kulturne dediščine"
    ],
    "client": "Javni zavod Ljubljanski grad",
    "location": "Ljubljanski grad",
    "workType": "Rušenje in prenova objekta",
    "year": "2015"
  },
  "muzej-in-prezentacija-lutk-na-ljubljanskem-gradu": {
    "categories": [
      "Javni objekti",
      "Objekti kulturne dediščine"
    ],
    "client": "Mestna občina Ljubljana",
    "location": "Ljubljanski grad",
    "workType": "GOI dela",
    "year": "2014"
  },
  "porocne-dvorane-na-ljubljanskem-gradu": {
    "categories": [
      "Javni objekti",
      "Objekti kulturne dediščine"
    ],
    "client": "Javni zavod Ljubljanski grad",
    "location": "Ljubljana",
    "workType": "Gradbeno obrtniška in inštalaterska dela, potrebna za obnovo poročnih dvoran",
    "year": "2014"
  },
  "pokrito-igrisce-druzinski-center-mala-ulica": {
    "categories": [
      "Javni objekti",
      "Objekti kulturne dediščine"
    ],
    "client": "Mestna občina Ljubljana",
    "location": "Ljubljana",
    "workType": "Rekonstrukcija",
    "year": "2012"
  },
  "solski-hotel-astoria-bled": {
    "categories": [
      "Javni objekti",
      "Poslovno industrijski objekti"
    ],
    "client": "Višja strokovna šola za gostinstvo in turizem Bled",
    "location": "Bled",
    "workType": "obrtniška dela – tlakarska dela, mizarska dela, elektro inštalacije, montaža oken in vrat, montaža opreme hotela",
    "year": "2012"
  },
  "siritev-pokopalisca-vic-goi-dela": {
    "categories": [
      "Javni objekti"
    ],
    "client": "Mestna občina Ljubljana",
    "location": "Ljubljana",
    "workType": "Širitev Pokopališča Vič",
    "year": ""
  },
  "zdravstveni-dom-slovenska-bistrica": {
    "categories": [
      "Javni objekti",
      "Zdravstveni domovi"
    ],
    "client": "Občina Slovenska Bistrica",
    "location": "Slovenska Bistrica",
    "workType": "Energetska sanacija",
    "year": "2013"
  },
  "dso-ljubljana-bezigrad": {
    "categories": [
      "Domovi za starejše",
      "Javni objekti"
    ],
    "client": "Dom starejših občanov Ljubljana - Bežigrad",
    "location": "Ljubljana - Bežigrad",
    "workType": "Rekonstrukcija z dobavo in montažo pohištva",
    "year": ""
  },
  "dso-ljubljana-vic-rudnik-enota-bokalce": {
    "categories": [
      "Domovi za starejše",
      "Javni objekti"
    ],
    "client": "Dom starejših občanov Ljubljana Vič-Rudnik",
    "location": "Ljubljana, Bokalce",
    "workType": "Rekonstrukcija in dozidava",
    "year": "2017"
  },
  "os-nove-fuzine": {
    "categories": [
      "Javni objekti",
      "Šole"
    ],
    "client": "Mestna občina Ljubljana",
    "location": "",
    "workType": "Celovita prenova in nadgradnja OŠ Nove Fužine, pri kateri se upoštevajo okoljski vidiki",
    "year": "2020"
  },
  "vrtec-laporje": {
    "categories": [
      "Javni objekti",
      "Vrtci"
    ],
    "client": "Občina Slovenska Bistrica",
    "location": "Slovenska Bistrica",
    "workType": "",
    "year": "2023"
  },
  "izgradnja-sportnega-centra-luce": {
    "categories": [
      "Dvorane",
      "Javni objekti"
    ],
    "client": "Občina Luče",
    "location": "Luče",
    "workType": "GOI dela za izgradnjo nove športner dvorane",
    "year": "2022"
  },
  "sportna-dvorana-podmezakla": {
    "categories": [
      "Dvorane",
      "Javni objekti"
    ],
    "client": "Občina Jesenice",
    "location": "Podmežakla",
    "workType": "Rekonstrukcija",
    "year": "2013"
  },
  "sportni-park-kodeljevo": {
    "categories": [
      "Dvorane",
      "Javni objekti"
    ],
    "client": "RESALTA d.o.o.",
    "location": "Ljubljana - Kodeljevo",
    "workType": "Energetska sanacija",
    "year": "2018"
  },
  "vecnamenska-dvorana-os-koroski-jeklarji-podruznica-kotlje": {
    "categories": [
      "Dvorane",
      "Javni objekti"
    ],
    "client": "Občina Ravne na Koroškem",
    "location": "Kotlje, Ravne na Koroškem",
    "workType": "GOI dela pri novogradnji",
    "year": "2023"
  },
  "dvorana-za-kulturne-druzbene-in-sportne-aktivnosti-gorenja-vas": {
    "categories": [
      "Dvorane",
      "Javni objekti"
    ],
    "client": "Občina Gorenja vas – Poljane",
    "location": "Gorenja vas - Poljane",
    "workType": "GOI dela za novogradnjo dvorane",
    "year": ""
  },
  "telovadnica-v-os-branik": {
    "categories": [
      "Dvorane",
      "Javni objekti"
    ],
    "client": "Mestna občina Nova Gorica",
    "location": "Branik",
    "workType": "Energetska sanacija",
    "year": "2018"
  },
  "telovadnica-os-maksa-pecarja": {
    "categories": [
      "Dvorane",
      "Javni objekti"
    ],
    "client": "Mestna občina Ljubljana",
    "location": "Ljubljana - Črnuče",
    "workType": "Novogradnja",
    "year": ""
  },
  "os-kolezija-celovita-sanacija-objekta-na-splitski-12": {
    "categories": [
      "Javni objekti",
      "Šole"
    ],
    "client": "MESTNA OBČINA LJUBLJANA",
    "location": "Ljubljana – Kolezija",
    "workType": "",
    "year": ""
  },
  "celovita-sanacija-in-nadgradnja-os-nove-fuzine": {
    "categories": [
      "Javni objekti",
      "Šole"
    ],
    "client": "MESTNA OBČINA LJUBLJANA, Mestni trg 1, 1000 Ljubljana",
    "location": "Ljubljana, Nove Fužine",
    "workType": "",
    "year": "2021"
  },
  "glasbena-sola-slovenj-gradec": {
    "categories": [
      "Javni objekti",
      "Šole"
    ],
    "client": "Mestna občina Slovenj Gradec",
    "location": "Slovenj Gradec",
    "workType": "Novogradnja glasbene šole",
    "year": "2014"
  },
  "osnovna-sola-vide-pregarc": {
    "categories": [
      "Javni objekti",
      "Šole"
    ],
    "client": "Mestna občina Ljubljana",
    "location": "Ljubljana",
    "workType": "Gradnja in rekonstrukcija s energetsko sanacijo",
    "year": "2014"
  },
  "osnovna-sola-cirila-kosmaca": {
    "categories": [
      "Javni objekti",
      "Šole"
    ],
    "client": "Občina Piran",
    "location": "Piran",
    "workType": "Energetska sanacija",
    "year": "2013"
  },
  "solski-center-ljubljana-askerceva": {
    "categories": [
      "Javni objekti",
      "Šole"
    ],
    "client": "Šolski center Ljubljana",
    "location": "Ljubljana",
    "workType": "Sanacijska dela energetske sanacije",
    "year": "2017"
  },
  "osnovna-sola-cerkno": {
    "categories": [
      "Javni objekti",
      "Šole"
    ],
    "client": "Občina Cerkno",
    "location": "Cerkno",
    "workType": "Energetska sanacija in prenova OŠ Cerkno",
    "year": "2017"
  },
  "osnovna-sola-maksa-pecarja": {
    "categories": [
      "Javni objekti",
      "Šole"
    ],
    "client": "Mestna občina Ljubljana, Petrol d.d.",
    "location": "Ljubljana - Črnuče",
    "workType": "Rekonstrukcija in energetska sanacija OŠ n.h. Maksa Pečarja",
    "year": "2018"
  },
  "celovita-prenova-objekt-vrtec-sentvid-enota-sapramiska": {
    "categories": [
      "Javni objekti",
      "Vrtci"
    ],
    "client": "MESTNA OBČINA LJUBLJANA",
    "location": "Ljubljana - Šentvid",
    "workType": "",
    "year": "2021"
  },
  "vrtec-otona-zupancica-enota-cebelica": {
    "categories": [
      "Javni objekti",
      "Vrtci"
    ],
    "client": "Mestna občina Ljubljana",
    "location": "Ljubljana - Bizovik",
    "workType": "Rušitev obstoječega in novogradnja lesenega vrtca",
    "year": "2014"
  },
  "vrtec-dornberk": {
    "categories": [
      "Javni objekti",
      "Vrtci"
    ],
    "client": "Mestna občina Nova Gorica",
    "location": "Dornberk",
    "workType": "GOI dela za energetsko sanacijo vrtca Dornberk",
    "year": "2018"
  },
  "gradnja-podruznicne-sole-in-vrtca-turjak": {
    "categories": [
      "Javni objekti",
      "Šole",
      "Vrtci"
    ],
    "client": "Občina Velike Lašče",
    "location": "Velike Lašče",
    "workType": "Izgradnja podružnične šole in vrtca",
    "year": ""
  },
  "vrtec-sentjernej": {
    "categories": [
      "Javni objekti",
      "Vrtci"
    ],
    "client": "Občina Šentjernej",
    "location": "Šentjernej",
    "workType": "GOI dela pri novogradnji",
    "year": ""
  }
} as const;

export type ProjectMeta = typeof projectMeta;
