/* eslint-disable no-console */
import fs from "node:fs";
import path from "node:path";

import { projects } from "../src/content/projects.generated";
import { fetchProjectMeta } from "../src/lib/wp/fetchProjectMeta";

function decodeHtmlEntities(s?: string) {
  if (!s) return s;

  return s
    .replace(/&#8211;|&ndash;/g, "–")
    .replace(/&#8212;|&mdash;/g, "—")
    .replace(/&#8230;|&hellip;/g, "…")
    .replace(/&#8217;|&rsquo;/g, "’")
    .replace(/&#8216;|&lsquo;/g, "‘")
    .replace(/&quot;/g, '"')
    .replace(/&#039;|&apos;/g, "'")
    .replace(/&amp;/g, "&")
    .replace(/&nbsp;|&#160;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function toTs(meta: Record<string, any>) {
  return `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/gen-project-meta.ts

export const projectMeta = ${JSON.stringify(meta, null, 2)} as const;

export type ProjectMeta = typeof projectMeta;
`;
}

async function main() {
  const out: Record<string, any> = {};

  console.log(`Found ${projects.length} projects\n`);

  for (let i = 0; i < projects.length; i++) {
    const p = projects[i];
    const slug = p.slug;

    const url = `https://demaplus.si/reference/${slug}/`;

    process.stdout.write(`[${i + 1}/${projects.length}] ${slug} ... `);

    try {
      const meta = await fetchProjectMeta(url);

      let year = meta.year;
      if (year && /\d{4}/.test(year)) {
        const m = year.match(/\d{4}/);
        if (m) year = m[0];
      }

      out[slug] = {
        categories: (meta.categories ?? [])
          .map((c) => decodeHtmlEntities(c))
          .filter(Boolean),
        client: decodeHtmlEntities(meta.client ?? "") ?? "",
        location: decodeHtmlEntities(meta.location ?? "") ?? "",
        workType: decodeHtmlEntities(meta.workType ?? "") ?? "",
        year: year ?? "",
      };

      console.log("OK");
    } catch (e: any) {
      console.log("FAIL");
      out[slug] = { error: String(e) };
      console.error(`  -> ${slug} failed:`, e?.message ?? e);
    }
  }

  const targetPath = path.join(
    process.cwd(),
    "src/content/projects.meta.generated.ts"
  );

  fs.writeFileSync(targetPath, toTs(out), "utf8");

  console.log(`\n✔ Wrote: ${targetPath}\n`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});